### PR TITLE
Fix compilation error in Ubuntu 14.04.

### PR DESCRIPTION
**Pull request by domob1812**
Fix a compilation error in Ubuntu 14.04 - see https://github.com/chronokings/huntercoin/pull/50.  I've tested that the code still works / compiles for me (and the added #include shouldn't hurt), but I can't confirm that it does indeed fix the problem also for Namecoin.  Please, someone test this.  I got reports that the current HEAD fails to build on Ubuntu 14.04 with the same error that appears in Huntercoin.

### CODE REVIEW

**Comment by crosser** [comment]
Fixes the link error for me, resulting binary works.

**Comment by phelixbtc** [comment]
Compiles on Windows, too. ACK
